// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: wibuwallpaper/v1/topic_api.proto

package wibuwallpaperv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListTopicsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListTopicsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTopicsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTopicsRequestMultiError, or nil if none found.
func (m *ListTopicsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTopicsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageToken

	if len(errors) > 0 {
		return ListTopicsRequestMultiError(errors)
	}

	return nil
}

// ListTopicsRequestMultiError is an error wrapping multiple validation errors
// returned by ListTopicsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListTopicsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTopicsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTopicsRequestMultiError) AllErrors() []error { return m }

// ListTopicsRequestValidationError is the validation error returned by
// ListTopicsRequest.Validate if the designated constraints aren't met.
type ListTopicsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTopicsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTopicsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTopicsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTopicsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTopicsRequestValidationError) ErrorName() string {
	return "ListTopicsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListTopicsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTopicsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTopicsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTopicsRequestValidationError{}

// Validate checks the field values on ListTopicsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListTopicsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTopicsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTopicsResponseMultiError, or nil if none found.
func (m *ListTopicsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTopicsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTopics() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListTopicsResponseValidationError{
						field:  fmt.Sprintf("Topics[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListTopicsResponseValidationError{
						field:  fmt.Sprintf("Topics[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListTopicsResponseValidationError{
					field:  fmt.Sprintf("Topics[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListTopicsResponseMultiError(errors)
	}

	return nil
}

// ListTopicsResponseMultiError is an error wrapping multiple validation errors
// returned by ListTopicsResponse.ValidateAll() if the designated constraints
// aren't met.
type ListTopicsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTopicsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTopicsResponseMultiError) AllErrors() []error { return m }

// ListTopicsResponseValidationError is the validation error returned by
// ListTopicsResponse.Validate if the designated constraints aren't met.
type ListTopicsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTopicsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTopicsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTopicsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTopicsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTopicsResponseValidationError) ErrorName() string {
	return "ListTopicsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListTopicsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTopicsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTopicsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTopicsResponseValidationError{}
