// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pixiv/v1/artwork.proto

package pixivv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Artwork with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Artwork) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Artwork with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ArtworkMultiError, or nil if none found.
func (m *Artwork) ValidateAll() error {
	return m.validate(true)
}

func (m *Artwork) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for AgeLimit

	// no validation rules for UserId

	for idx, item := range m.GetImageUrls() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ArtworkValidationError{
						field:  fmt.Sprintf("ImageUrls[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ArtworkValidationError{
						field:  fmt.Sprintf("ImageUrls[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ArtworkValidationError{
					field:  fmt.Sprintf("ImageUrls[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ArtworkMultiError(errors)
	}

	return nil
}

// ArtworkMultiError is an error wrapping multiple validation errors returned
// by Artwork.ValidateAll() if the designated constraints aren't met.
type ArtworkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArtworkMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArtworkMultiError) AllErrors() []error { return m }

// ArtworkValidationError is the validation error returned by Artwork.Validate
// if the designated constraints aren't met.
type ArtworkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArtworkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArtworkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArtworkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArtworkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArtworkValidationError) ErrorName() string { return "ArtworkValidationError" }

// Error satisfies the builtin error interface
func (e ArtworkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArtwork.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArtworkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArtworkValidationError{}

// Validate checks the field values on ImageUrl with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ImageUrl) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ImageUrl with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ImageUrlMultiError, or nil
// if none found.
func (m *ImageUrl) ValidateAll() error {
	return m.validate(true)
}

func (m *ImageUrl) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Thumb

	// no validation rules for Small

	// no validation rules for Regular

	// no validation rules for Original

	// no validation rules for Width

	// no validation rules for Height

	// no validation rules for Mini

	// no validation rules for OriginalSize

	if len(errors) > 0 {
		return ImageUrlMultiError(errors)
	}

	return nil
}

// ImageUrlMultiError is an error wrapping multiple validation errors returned
// by ImageUrl.ValidateAll() if the designated constraints aren't met.
type ImageUrlMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ImageUrlMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ImageUrlMultiError) AllErrors() []error { return m }

// ImageUrlValidationError is the validation error returned by
// ImageUrl.Validate if the designated constraints aren't met.
type ImageUrlValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ImageUrlValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ImageUrlValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ImageUrlValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ImageUrlValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ImageUrlValidationError) ErrorName() string { return "ImageUrlValidationError" }

// Error satisfies the builtin error interface
func (e ImageUrlValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sImageUrl.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ImageUrlValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ImageUrlValidationError{}
