// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pixiv/v1/artwork_api.proto

package pixivv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetArtworkResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetArtworkResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArtworkResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetArtworkResponseMultiError, or nil if none found.
func (m *GetArtworkResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArtworkResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetArtwork() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetArtworkResponseValidationError{
						field:  fmt.Sprintf("Artwork[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetArtworkResponseValidationError{
						field:  fmt.Sprintf("Artwork[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetArtworkResponseValidationError{
					field:  fmt.Sprintf("Artwork[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetArtworkResponseMultiError(errors)
	}

	return nil
}

// GetArtworkResponseMultiError is an error wrapping multiple validation errors
// returned by GetArtworkResponse.ValidateAll() if the designated constraints
// aren't met.
type GetArtworkResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArtworkResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArtworkResponseMultiError) AllErrors() []error { return m }

// GetArtworkResponseValidationError is the validation error returned by
// GetArtworkResponse.Validate if the designated constraints aren't met.
type GetArtworkResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArtworkResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArtworkResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArtworkResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArtworkResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArtworkResponseValidationError) ErrorName() string {
	return "GetArtworkResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetArtworkResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArtworkResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArtworkResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArtworkResponseValidationError{}

// Validate checks the field values on GetArtworkRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetArtworkRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArtworkRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetArtworkRequestMultiError, or nil if none found.
func (m *GetArtworkRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArtworkRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ArtworkId

	if len(errors) > 0 {
		return GetArtworkRequestMultiError(errors)
	}

	return nil
}

// GetArtworkRequestMultiError is an error wrapping multiple validation errors
// returned by GetArtworkRequest.ValidateAll() if the designated constraints
// aren't met.
type GetArtworkRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArtworkRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArtworkRequestMultiError) AllErrors() []error { return m }

// GetArtworkRequestValidationError is the validation error returned by
// GetArtworkRequest.Validate if the designated constraints aren't met.
type GetArtworkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArtworkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArtworkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArtworkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArtworkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArtworkRequestValidationError) ErrorName() string {
	return "GetArtworkRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetArtworkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArtworkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArtworkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArtworkRequestValidationError{}
