// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pinterest/v1/pinterest.proto

package pinterestv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Profile with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Profile) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Profile with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ProfileMultiError, or nil if none found.
func (m *Profile) ValidateAll() error {
	return m.validate(true)
}

func (m *Profile) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FirstName

	// no validation rules for Id

	// no validation rules for Username

	// no validation rules for FullName

	// no validation rules for ImageMediumUrl

	if len(errors) > 0 {
		return ProfileMultiError(errors)
	}

	return nil
}

// ProfileMultiError is an error wrapping multiple validation errors returned
// by Profile.ValidateAll() if the designated constraints aren't met.
type ProfileMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProfileMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProfileMultiError) AllErrors() []error { return m }

// ProfileValidationError is the validation error returned by Profile.Validate
// if the designated constraints aren't met.
type ProfileValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProfileValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProfileValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProfileValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProfileValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProfileValidationError) ErrorName() string { return "ProfileValidationError" }

// Error satisfies the builtin error interface
func (e ProfileValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProfile.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProfileValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProfileValidationError{}

// Validate checks the field values on VideoPin with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VideoPin) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VideoPin with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VideoPinMultiError, or nil
// if none found.
func (m *VideoPin) ValidateAll() error {
	return m.validate(true)
}

func (m *VideoPin) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Description

	// no validation rules for Url

	// no validation rules for ThumbnailUrl

	// no validation rules for VideoUrl

	// no validation rules for StaticUrl

	// no validation rules for Width

	// no validation rules for Height

	// no validation rules for Duration

	if all {
		switch v := interface{}(m.GetOriginPinner()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VideoPinValidationError{
					field:  "OriginPinner",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VideoPinValidationError{
					field:  "OriginPinner",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOriginPinner()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VideoPinValidationError{
				field:  "OriginPinner",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for DominantColor

	if len(errors) > 0 {
		return VideoPinMultiError(errors)
	}

	return nil
}

// VideoPinMultiError is an error wrapping multiple validation errors returned
// by VideoPin.ValidateAll() if the designated constraints aren't met.
type VideoPinMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VideoPinMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VideoPinMultiError) AllErrors() []error { return m }

// VideoPinValidationError is the validation error returned by
// VideoPin.Validate if the designated constraints aren't met.
type VideoPinValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VideoPinValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VideoPinValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VideoPinValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VideoPinValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VideoPinValidationError) ErrorName() string { return "VideoPinValidationError" }

// Error satisfies the builtin error interface
func (e VideoPinValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVideoPin.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VideoPinValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VideoPinValidationError{}
