// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pinterest/v1/pinterest_api.proto

package pinterestv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetVideoPinRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetVideoPinRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetVideoPinRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetVideoPinRequestMultiError, or nil if none found.
func (m *GetVideoPinRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetVideoPinRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PinId

	if len(errors) > 0 {
		return GetVideoPinRequestMultiError(errors)
	}

	return nil
}

// GetVideoPinRequestMultiError is an error wrapping multiple validation errors
// returned by GetVideoPinRequest.ValidateAll() if the designated constraints
// aren't met.
type GetVideoPinRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetVideoPinRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetVideoPinRequestMultiError) AllErrors() []error { return m }

// GetVideoPinRequestValidationError is the validation error returned by
// GetVideoPinRequest.Validate if the designated constraints aren't met.
type GetVideoPinRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetVideoPinRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetVideoPinRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetVideoPinRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetVideoPinRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetVideoPinRequestValidationError) ErrorName() string {
	return "GetVideoPinRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetVideoPinRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetVideoPinRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetVideoPinRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetVideoPinRequestValidationError{}

// Validate checks the field values on GetVideoPinResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetVideoPinResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetVideoPinResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetVideoPinResponseMultiError, or nil if none found.
func (m *GetVideoPinResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetVideoPinResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetVideoPin()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetVideoPinResponseValidationError{
					field:  "VideoPin",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetVideoPinResponseValidationError{
					field:  "VideoPin",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetVideoPin()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetVideoPinResponseValidationError{
				field:  "VideoPin",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetVideoPinResponseMultiError(errors)
	}

	return nil
}

// GetVideoPinResponseMultiError is an error wrapping multiple validation
// errors returned by GetVideoPinResponse.ValidateAll() if the designated
// constraints aren't met.
type GetVideoPinResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetVideoPinResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetVideoPinResponseMultiError) AllErrors() []error { return m }

// GetVideoPinResponseValidationError is the validation error returned by
// GetVideoPinResponse.Validate if the designated constraints aren't met.
type GetVideoPinResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetVideoPinResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetVideoPinResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetVideoPinResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetVideoPinResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetVideoPinResponseValidationError) ErrorName() string {
	return "GetVideoPinResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetVideoPinResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetVideoPinResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetVideoPinResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetVideoPinResponseValidationError{}
